---
- name: testing remote src
  hosts: all:!controller
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
  - name: copying from /etc to /tmp in clients
    copy:
      src: /etc/testfile
      dest: /tmp
      remote_src: yes